### PR TITLE
Added alpha_actions to iterate through alpha vectors and actions

### PR DESCRIPTION
**Pull request by zsunberg**

### CODE REVIEW

**Comment by rejuvyesh** [comment]
~I am not sure of the utility. Shouldn't `zip` be enough?~

I guess we don't have any API to access the internals of that struct.

**Comment by zsunberg** [comment]
@rejuvyesh Thanks for commenting!

> I guess we don't have any API to access the internals of that struct.

Yeah, that was the reason. I was plotting some alpha vectors and realized there was no way to do this without accessing the fields directly.

Do you think we should also add `alphas(p)` or `alphavectors(p)` to access the vectors only without the actions?

**Comment by rejuvyesh** [comment]
`alpahavectors` should definitely be there.

**Comment by zsunberg** [comment]
Ok, I think `alphavectors` and `alphapairs` are the best names. Does that sound good?

**Pull request merged**
